Repository ALPHAVIO/WordNook, pull requests merged in 2021-04, with the labels that each got.

#541 Remove repeated scripts to improve load time
  views/partials/footer.ejs
  views/partials/header.ejs
Labels: PR: unreviewed

#542 Update .prettierrc.json
  .prettierrc.json
Labels: PR: unreviewed

#548 placeholder changed
  views/home.ejs
Labels: PR: unreviewed

#549 chore: update deploy branch
  .prettierrc.json
  public/darkMode.js
  public/landBot.js
  public/loader.js
  public/postScript.js
  views/home.ejs
  views/partials/footer.ejs
  views/partials/header.ejs
  views/post.ejs
Labels: PR: unreviewed

#558 logo adjusted
  public/css/styles.css
  public/images/BlogSiteLogo-2.png
  views/partials/header.ejs
Labels: GSSOC21, Level2, PR: reviewed-approved

#554 fix(dark-mode) : darkmode was being applied on images
  public/css/styles.css
  public/darkMode.js
  views/partials/footer.ejs
  views/partials/header.ejs
  views/post.ejs
Labels: PR: unreviewed

#561 chore: update deploy branch
  .prettierignore
  public/css/styles.css
  public/darkMode.js
  public/images/BlogSiteLogo-2.png
  views/partials/footer.ejs
  views/partials/header.ejs
  views/post.ejs
Labels: PR: unreviewed

#555 Removed confirm Password from model
  models/User.model.js
  public/checkPasswordMatch.js
  routes/user.router.js
  views/partials/footer.ejs
  views/signUp.ejs
Labels: PR: reviewed-approved

#563 chore: update deploy
  models/User.model.js
  package-lock.json
  package.json
  public/checkPasswordMatch.js
  routes/user.router.js
  views/partials/footer.ejs
  views/signUp.ejs
Labels: PR: unreviewed

#568 add(option-select): compose post section
  views/compose.ejs
Labels: GSSOC21, PR: unreviewed

#572 Added hover effect on filter button
  public/css/styles.css
  views/home.ejs
Labels: PR: reviewed-approved

#571 Bed hover effect in the Buttons of Navbar
  public/css/styles.css
Labels: PR: unreviewed

#578 chore: update deploy
  public/css/styles.css
  views/compose.ejs
  views/home.ejs
Labels: PR: unreviewed

#580 Fixed the navbar toggle bug
  views/partials/header.ejs
Labels: PR: reviewed-approved

#583 Removed logo bug
  views/partials/header.ejs
Labels: PR: reviewed-approved

#589 add RushanKhan1 as a Maintainer
  README.md
Labels: PR: unreviewed

#587 [UI]:Logo redirects to home
  public/css/styles.css
  views/partials/header.ejs
Labels: PR: reviewed-approved

#582 Added capitalize function
  routes/index.router.js
Labels: PR: unreviewed

#591 chore: update deploy
  README.md
  public/css/styles.css
  routes/index.router.js
  views/partials/header.ejs
Labels: PR: unreviewed

#598 Added like functionality.
  app.js
  config/db.js
  middlewares/auth.js
  middlewares/mail.js
  models/Blog.model.js
  package-lock.json
  routes/post.router.js
  views/post.ejs
Labels: PR: unreviewed

#599 fixed the margin of the button
  public/css/styles.css
Labels: PR: reviewed-approved

#559 Implemented follow and unfollow feature
  models/User.model.js
  routes/user.router.js
  views/author.ejs
  views/dashboard.ejs
Labels: GSSOC21, Level3, PR: unreviewed

#574 moved inline styles from ejs files to styles.css issue#553
  public/css/styles.css
  views/404.ejs
  views/contact.ejs
  views/edit.ejs
  views/home.ejs
  views/partials/footer.ejs
  views/partials/posts.ejs
  views/post.ejs
Labels: GSSOC21, Level3, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed

#604 Add .slugfile
  .slugignore
  uploads/2021-03-23T19-17-06.832Zmahadbt.jpg
Labels: PR: unreviewed

#605 chore: update deploy
  .slugignore
  app.js
  config/db.js
  middlewares/auth.js
  middlewares/mail.js
  models/Blog.model.js
  models/User.model.js
  package-lock.json
  package.json
  public/css/styles.css
  routes/post.router.js
  routes/user.router.js
  uploads/2021-03-23T19-17-06.832Zmahadbt.jpg
  views/404.ejs
  views/author.ejs
  views/contact.ejs
  views/dashboard.ejs
  views/edit.ejs
  views/home.ejs
  views/partials/footer.ejs
  views/partials/posts.ejs
  views/post.ejs
Labels: PR: unreviewed

#603 Redirecting a not logged-in user to /login while accessing other user profile
  routes/user.router.js
Labels: GSSOC21, Level2, PR: reviewed-approved

#608 Update styles.css
  public/css/styles.css
  views/home.ejs
Labels: GSSOC21, Level2, PR: reviewed-approved

#584 Custom Scrollbar Added
  public/css/styles.css
Labels: GSSOC21, Level2, PR: reviewed-approved

#612 Add code linter: Eslint
  .eslintrc.json
  .prettierignore
  app.js
  middlewares/auth.js
  middlewares/mail.js
  models/Blog.model.js
  models/User.model.js
  package-lock.json
  package.json
  public/checkPasswordMatch.js
  public/darkMode.js
  public/landBot.js
  public/loader.js
  public/postScript.js
  routes/index.router.js
  routes/post.router.js
  routes/user.router.js
Labels: PR: unreviewed

#614 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: unreviewed

#615 Create .eslintignore
  .eslintignore
Labels: PR: unreviewed

#617 added likes counter functionality
  models/User.model.js
  routes/post.router.js
  views/partials/posts.ejs
  views/post.ejs
Labels: PR: reviewed-approved

#621 chore: update deploy branch
  .eslintignore
  .eslintrc.json
  .github/PULL_REQUEST_TEMPLATE.md
  .prettierignore
  .slugignore
  app.js
  middlewares/auth.js
  middlewares/mail.js
  models/Blog.model.js
  models/User.model.js
  package-lock.json
  package.json
  public/checkPasswordMatch.js
  public/css/styles.css
  public/darkMode.js
  public/landBot.js
  public/loader.js
  public/postScript.js
  routes/index.router.js
  routes/post.router.js
  routes/user.router.js
  views/home.ejs
  views/partials/posts.ejs
  views/post.ejs
Labels: PR: unreviewed

#622 Update .deepsource.toml
  .deepsource.toml
Labels: PR: unreviewed

#624 Show liked posts on dashboard and user profile
  routes/user.router.js
  views/author.ejs
  views/dashboard.ejs
Labels: PR: unreviewed

#625 Validation for First and Last name
  routes/user.router.js
Labels: GSSOC21, PR: unreviewed

#632 Update README.md
  README.md
Labels: PR: unreviewed

#629 issue #626 show 1 like if there is 1 like else show x likes
  views/post.ejs
Labels: GSSOC21, Level2, PR: reviewed-approved

#631 Email Verification Method
  README.md
  models/User.model.js
  routes/user.router.js
Labels: GSSOC21, Level3, PR: reviewed-changes-requested, PR: unreviewed

#635 changed bottom to 0.6rem
  public/darkMode.js
Labels: GSSOC21, Level2, PR: unreviewed

#650 solved issue regarding login
  package-lock.json
  routes/user.router.js
Labels: PR: unreviewed

#646 added show/hide password
  public/css/styles.css
  public/js/showHidePassword.js
  views/logIn.ejs
  views/partials/footer.ejs
Labels: GSSOC21, Level2, PR: unreviewed

#653 Height of navbar updated
  public/css/styles.css
Labels: GSSOC21, Level2, PR: unreviewed

#659 Remove email verification code
  models/User.model.js
  routes/user.router.js
Labels: PR: unreviewed

#660 chore: update deploy
  models/User.model.js
  public/css/styles.css
  public/js/showHidePassword.js
  routes/index.router.js
  routes/post.router.js
  routes/user.router.js
  views/auth/logIn.ejs
  views/auth/signUp.ejs
  views/navitems/about.ejs
  views/navitems/contact.ejs
  views/navitems/home.ejs
  views/partials/footer.ejs
  views/postitems/category.ejs
  views/postitems/compose.ejs
  views/postitems/edit.ejs
  views/postitems/post.ejs
  views/useritems/author.ejs
  views/useritems/dashboard.ejs
  views/useritems/read-profile.ejs
Labels: PR: unreviewed

#658 refactor(user validation) : validations used in user.js
  middlewares/validations/user.js
  routes/user.router.js
Labels: PR: reviewed-approved

#665 Number of views functionality added
  models/Blog.model.js
  routes/post.router.js
  views/postitems/post.ejs
Labels: PR: reviewed-approved

#667 Moved js files from public folder to public/js folder
  public/js/checkPasswordMatch.js
  public/js/darkMode.js
  public/js/landBot.js
  public/js/loader.js
  public/js/postScript.js
  views/auth/logIn.ejs
  views/auth/signUp.ejs
  views/partials/footer.ejs
  views/postitems/post.ejs
Labels: PR: reviewed-approved

#666 Added user profile edit button on dashboard
  views/partials/header.ejs
  views/useritems/dashboard.ejs
Labels: GSSOC21, Level2, PR: reviewed-approved

#669 chore: update deploy
  README.md
  middlewares/validations/user.js
  models/Blog.model.js
  public/js/checkPasswordMatch.js
  public/js/darkMode.js
  public/js/landBot.js
  public/js/loader.js
  public/js/postScript.js
  routes/post.router.js
  routes/user.router.js
  views/auth/logIn.ejs
  views/auth/signUp.ejs
  views/partials/footer.ejs
  views/partials/header.ejs
  views/postitems/post.ejs
  views/useritems/dashboard.ejs
Labels: PR: unreviewed

#672 removed width from form group
  public/css/styles.css
Labels: PR: unreviewed

#679 Added show password feature on signup and edit profile page issue#668
  public/js/showHidePassword.js
  views/auth/signUp.ejs
  views/useritems/read-profile.ejs
Labels: PR: reviewed-approved

#687 issue 640 fixed - Changed border colors of input boxes
  public/css/styles.css
Labels: GSSOC21, PR: reviewed-approved

#686 issue 565 fixed - added placeholder property to contact form
  views/navitems/contact.ejs
Labels: PR: unreviewed

#688 Scroll to top
  public/css/styles.css
  public/js/autoScrollUp.js
  views/partials/footer.ejs
Labels: GSSOC21, Level2, PR: reviewed-approved

#691 chore: update deploy
  package-lock.json
  package.json
  public/css/styles.css
  public/js/autoScrollUp.js
  public/js/showHidePassword.js
  views/auth/signUp.ejs
  views/navitems/contact.ejs
  views/partials/footer.ejs
  views/useritems/read-profile.ejs
Labels: PR: unreviewed

#696 Update README.md
  README.md
Labels: PR: unreviewed

#699 Delete comment restriction
  routes/post.router.js
  views/postitems/post.ejs
Labels: GSSOC21, Level2, PR: reviewed-approved

#700 centered the page number component issue#483
  views/navitems/home.ejs
Labels: PR: reviewed-approved

#697 Flagging comments feature issue#411
  public/css/styles.css
  routes/post.router.js
  views/postitems/post.ejs
Labels: GSSOC21, Level3, PR: unreviewed

#701 chore: update deploy
  README.md
  package-lock.json
  package.json
  public/css/styles.css
  routes/post.router.js
  views/navitems/home.ejs
  views/postitems/post.ejs
Labels: PR: unreviewed

#703 Styled Scroll to Top Button
  public/css/styles.css
Labels: PR: reviewed-approved

#708 navbar color fixed
  public/css/styles.css
  views/partials/header.ejs
Labels: GSSOC21, Level2, PR: unreviewed

#707 fixed internal server error on uploading images while posting blogs
  uploads/ALPHAVIO.png
Labels: GSSOC21, Level2, PR: unreviewed

#718 fixed inconsistency in font colors on dashboard
  public/css/styles.css
  views/useritems/dashboard.ejs
Labels: GSSOC21, PR: reviewed-approved

#720 Improved position of back-to-top arrow
  public/css/styles.css
Labels: PR: reviewed-approved

#722 Added z-index to back-to-top button
  public/css/styles.css
Labels: PR: unreviewed

#724 Fixed inconsistency in styling of like and comment buttons
  public/css/styles.css
  views/postitems/post.ejs
Labels: PR: reviewed-approved

#727 Lint the code and put assets in `.slugignore` to reduce build time
  .eslintignore
  .eslintrc.json
  .prettierrc.json
  .slugignore
  app.js
  config/db.js
  middlewares/auth.js
  middlewares/mail.js
  middlewares/validations/user.js
  models/Blog.model.js
  models/User.model.js
  package.json
  public/js/autoScrollUp.js
  public/js/checkPasswordMatch.js
  public/js/darkMode.js
  public/js/landBot.js
  public/js/loader.js
  public/js/postScript.js
  public/js/showHidePassword.js
  routes/index.router.js
  routes/post.router.js
  routes/user.router.js
Labels: PR: unreviewed

#730 Setup CI issue #723
  .eslintrc.json
  .github/workflows/node.js.yml
Labels: PR: unreviewed

#731 Update node version and add pre-commit hooks using husky
  package-lock.json
  package.json
Labels: PR: unreviewed

#732 chore: update deploy
  .eslintignore
  .eslintrc.json
  .github/workflows/node.js.yml
  .prettierrc.json
  .slugignore
  README.md
  app.js
  config/db.js
  middlewares/auth.js
  middlewares/mail.js
  middlewares/validations/user.js
  models/Blog.model.js
  models/User.model.js
  package-lock.json
  package.json
  public/css/styles.css
  public/js/autoScrollUp.js
  public/js/checkPasswordMatch.js
  public/js/darkMode.js
  public/js/landBot.js
  public/js/loader.js
  public/js/postScript.js
  public/js/showHidePassword.js
  routes/index.router.js
  routes/post.router.js
  routes/user.router.js
  uploads/ALPHAVIO.png
  views/postitems/post.ejs
  views/useritems/dashboard.ejs
Labels: PR: unreviewed

#734 Add badges to README
  README.md
Labels: PR: unreviewed

#735 Styled save and cancel button
  public/css/styles.css
  views/useritems/read-profile.ejs
Labels: PR: reviewed-approved

#725 Added User profile feature
  models/User.model.js
  public/css/styles.css
  public/images/Default_Profile.jpg
  routes/user.router.js
  views/auth/signUp.ejs
  views/useritems/author.ejs
  views/useritems/dashboard.ejs
  views/useritems/read-profile.ejs
Labels: GSSOC21, PR: reviewed-approved, PR: unreviewed

#738 fixed server issue on localhost
  routes/index.router.js
Labels: GSSOC21, Level2, PR: reviewed-changes-requested

#742 Update landBot.js
  public/js/landBot.js
Labels: PR: unreviewed

#747 Update node.js.yml
  .github/workflows/node.js.yml
Labels: PR: unreviewed

#748 Update node.js.yml
  .github/workflows/node.js.yml
Labels: PR: unreviewed

#749 updated website name from daily journal to wordnook wherever needed
  routes/index.router.js
  routes/post.router.js
  views/navitems/about.ejs
  views/partials/footer.ejs
  views/partials/header.ejs
Labels: PR: reviewed-approved

#741 added validation while updating profile
  middlewares/validations/user.js
  routes/user.router.js
  views/useritems/read-profile.ejs
Labels: GSSOC21, Level3, PR: reviewed-approved

#753 Update deploy
  .github/workflows/node.js.yml
  middlewares/validations/user.js
  public/js/landBot.js
  routes/user.router.js
  views/useritems/read-profile.ejs
Labels: PR: unreviewed

#761 issue 620 fixed - edited hover effect on social media icons
  public/css/styles.css
Labels: GSSOC21, PR: reviewed-approved

#763 Testimonial
  app.js
  dummy-data/testimonial.js
  public/css/styles.css
  routes/index.router.js
  routes/testimonial.router.js
  views/navitems/home.ejs
  views/partials/footer.ejs
  views/partials/testimonial.ejs
  views/postitems/testimonial-write.ejs
Labels: GSSOC21, Level3, PR: reviewed-approved

#764 issue #762 fixed - edited hover effect on footer links
  public/css/styles.css
  views/partials/footer.ejs
Labels: GSSOC21, Level2, PR: reviewed-approved, PR: unreviewed

#765 added password validation on signup and update route
  middlewares/validations/user.js
Labels: GSSOC21, Level2, PR: reviewed-approved

#767 fixed user profile issue on signup issue#766
  routes/user.router.js
Labels: GSSOC21, Level2, PR: reviewed-approved

#769 Update deploy
  app.js
  dummy-data/testimonial.js
  middlewares/validations/user.js
  package-lock.json
  package.json
  public/css/styles.css
  routes/index.router.js
  routes/testimonial.router.js
  routes/user.router.js
  views/navitems/home.ejs
  views/partials/footer.ejs
  views/partials/testimonial.ejs
  views/postitems/testimonial-write.ejs
Labels: PR: unreviewed

#775 reduced profile image size
  public/css/styles.css
Labels: GSSOC21, Level2, PR: reviewed-approved

#776 Testimonial btn styled
  public/css/styles.css
  views/partials/testimonial.ejs
Labels: GSSOC21, PR: reviewed-approved
