Repository ALPHAVIO/WordNook, pull requests merged in 2021-05, with the labels that each got.

#784 fixed comment-flag issue #783
  views/postitems/post.ejs
Labels: PR: reviewed-approved

#782 Share feature
  public/css/styles.css
  public/js/share.js
  views/partials/shareDialog.ejs
  views/postitems/post.ejs
Labels: GSSOC21, Level3, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed

#788 Added Testimonial Wall page (Testimonial backend)
  public/css/styles.css
  routes/testimonial.router.js
  views/partials/header.ejs
  views/testimonials/testimonial-wall.ejs
  views/testimonials/testimonial-write.ejs
Labels: GSSOC21, Level3, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed

#791 Update deploy
  .github/dependabot.yml
  package-lock.json
  package.json
  public/css/styles.css
  public/js/share.js
  routes/testimonial.router.js
  views/partials/header.ejs
  views/partials/shareDialog.ejs
  views/partials/testimonial.ejs
  views/postitems/post.ejs
  views/testimonials/testimonial-wall.ejs
  views/testimonials/testimonial-write.ejs
Labels: PR: unreviewed

#789 Add Steps to lint in Readme
  CONTRIBUTING.md
  README.md
Labels: PR: unreviewed

#794 margin between testimonial and footer is removed
  views/navitems/about.ejs
  views/navitems/contact.ejs
  views/partials/footer.ejs
Labels: GSSOC21, Level2, PR: reviewed-approved

#796 Update README.md
  README.md
Labels: PR: unreviewed

#798 Share button styled
  public/css/styles.css
  views/postitems/post.ejs
Labels: PR: reviewed-approved

#800 fixed email not updating bug and also added validation to email
  middlewares/validations/user.js
  views/useritems/read-profile.ejs
Labels: PR: reviewed-approved

#795 navigation button added to testimonial
  public/css/styles.css
  views/partials/testimonial.ejs
Labels: GSSOC21, Level3, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed

#797 Adds New Testimonials (Implement Backend for Testimonials)
  public/css/styles.css
  routes/testimonial.router.js
  views/partials/testimonial.ejs
  views/testimonials/testimonial-wall.ejs
  views/testimonials/testimonial-write.ejs
Labels: GSSOC21, Level3, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed

#803 alignment of content in footer
  public/css/styles.css
  views/partials/footer.ejs
Labels: PR: reviewed-approved

#807 Update Deploy
  CONTRIBUTING.md
  README.md
  middlewares/validations/user.js
  public/css/styles.css
  routes/testimonial.router.js
  views/navitems/about.ejs
  views/navitems/contact.ejs
  views/partials/footer.ejs
  views/partials/testimonial.ejs
  views/postitems/post.ejs
  views/testimonials/testimonial-wall.ejs
  views/testimonials/testimonial-write.ejs
  views/useritems/read-profile.ejs
Labels: PR: unreviewed

#816 Changed profile image size
  public/css/styles.css
Labels: GSSOC21, Level2, PR: reviewed-approved

#814 Added edit blog route
  routes/post.router.js
Labels: GSSOC21, Level2, PR: reviewed-approved

#818 Added instructions in README for lock file version 2
  README.md
Labels: PR: unreviewed

#819 Added delete profile image button
  public/css/styles.css
  routes/user.router.js
  views/useritems/dashboard.ejs
Labels: GSSOC21, Level3, PR: reviewed-approved

#824 Deploy changes
  .github/workflows/greetings.yml
  README.md
  package-lock.json
  package.json
  public/css/styles.css
  routes/post.router.js
  routes/user.router.js
  views/useritems/dashboard.ejs
Labels: PR: unreviewed

#825 Update README.md
  README.md
Labels: PR: unreviewed

#829 Show delete button only if user has profile picture
  views/useritems/dashboard.ejs
Labels: PR: reviewed-approved

#832 Updated banner
  README.md
  assets/New Banner.jpg
  assets/WordNook.png
Labels: PR: unreviewed

#821 added responsiveness to the site
  public/css/styles.css
  views/navitems/home.ejs
  views/partials/header.ejs
  views/partials/posts.ejs
Labels: GSSOC21, Level2, PR: reviewed-changes-requested

#839 Create request-info.yml
  .github/workflows/request-info.yml
Labels: PR: unreviewed

#836 social icons are enhanced
  public/css/styles.css
  views/partials/footer.ejs
Labels: GSSOC21, Level3, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed

#849 Create automerge.yml
  .github/workflows/automerge.yml
Labels: PR: unreviewed

#851 Deploy changes
  .github/workflows/automerge.yml
  .github/workflows/node.js.yml
  .github/workflows/request-info.yml
  README.md
  assets/New Banner.jpg
  assets/WordNook.png
  middlewares/validations/user.js
  package-lock.json
  package.json
  public/css/styles.css
  public/images/Default_Profile.jpg
  routes/user.router.js
  views/navitems/home.ejs
  views/partials/footer.ejs
  views/partials/header.ejs
  views/partials/posts.ejs
  views/useritems/dashboard.ejs
Labels: PR: unreviewed

#856 contact form updated
  public/css/styles.css
  views/navitems/contact.ejs
Labels: GSSOC21, Level3, PR: reviewed-approved

#868 input placeholder made responsive
  public/css/styles.css
Labels: PR: reviewed-approved

#870 Solved button positions issue
  views/navitems/home.ejs
Labels: PR: reviewed-approved

#841 Added wall button on home page
  public/css/styles.css
  views/navitems/home.ejs
  views/partials/header.ejs
Labels: PR: reviewed-approved

#871 responsiveness of carousel
  public/css/styles.css
Labels: PR: reviewed-approved

#872 Fixed social buttons size and clickability on mobile viewport issue#863
  public/css/styles.css
Labels: PR: reviewed-approved

#874 compose page enhanced
  public/css/styles.css
  views/postitems/compose.ejs
Labels: PR: reviewed-approved

#881 Deploy changes
  .prettierignore
  package-lock.json
  package.json
  public/css/styles.css
  views/navitems/contact.ejs
  views/navitems/home.ejs
  views/partials/header.ejs
  views/postitems/compose.ejs
Labels: PR: unreviewed

#882 Fixed sign up error
  routes/user.router.js
Labels: PR: unreviewed

#886 contact page bug fixed
  public/css/styles.css
  views/navitems/contact.ejs
Labels: PR: reviewed-approved

#885 Testimonial profile image styles updated
  middlewares/validations/user.js
  public/css/styles.css
  views/partials/testimonial.ejs
Labels: PR: reviewed-approved

#883 profile page enhanced
  public/css/styles.css
  views/useritems/read-profile.ejs
Labels: PR: reviewed-approved

#884 footer updated
  public/css/styles.css
Labels: PR: unreviewed

#888 Update deploy
  middlewares/validations/user.js
  public/css/styles.css
  routes/user.router.js
  views/navitems/contact.ejs
  views/partials/testimonial.ejs
  views/useritems/read-profile.ejs
Labels: PR: unreviewed

#890 Fix sign-up page rendering issue #889
  routes/user.router.js
  views/auth/signUp.ejs
Labels: PR: unreviewed

#891 Fix sign-up route issue #889
  routes/user.router.js
  views/auth/signUp.ejs
Labels: PR: unreviewed

#894 Improved blog post ui, added bootstrap badges and pills
  public/css/styles.css
  views/postitems/post.ejs
Labels: GSSOC21, Level2, PR: reviewed-approved

#897 dashboard page enhanced
  public/css/styles.css
  views/useritems/dashboard.ejs
Labels: PR: reviewed-approved

#901 fixed posts on home page by adding margin
  views/partials/posts.ejs
Labels: PR: reviewed-approved

#899 Created new comment model and modified routes accordingly
  models/Blog.model.js
  models/Comment.model.js
  routes/post.router.js
Labels: PR: reviewed-approved

#869 Styled text on profile page
  public/css/styles.css
Labels: PR: reviewed-approved

#896 Included a my following Blogs category
  routes/user.router.js
  views/useritems/dashboard.ejs
Labels: GSSOC21, Level3, PR: reviewed-approved

#903 Logo Changed
  assets/BlogSiteLogo-2 (Dark Mode).png
  assets/BlogSiteLogo-2.png
  public/css/styles.css
  public/images/BlogSiteLogo-2.png
  public/images/wordnook logo.png
  views/partials/header.ejs
Labels: GSSOC21, Level3, PR: reviewed-changes-requested, PR: unreviewed

#907 Deploy changes
  README.md
  assets/BlogSiteLogo-2 (Dark Mode).png
  assets/BlogSiteLogo-2.png
  models/Blog.model.js
  models/Comment.model.js
  package-lock.json
  package.json
  public/css/styles.css
  public/images/BlogSiteLogo-2.png
  public/images/wordnook logo.png
  routes/post.router.js
  routes/user.router.js
  views/partials/header.ejs
  views/partials/posts.ejs
  views/partials/testimonial.ejs
  views/postitems/post.ejs
  views/useritems/dashboard.ejs
Labels: PR: unreviewed

#887 Changed the background of testimonial
  public/css/styles.css
Labels: GSSOC21, Level2, PR: reviewed-approved

#915 Added reply section to Comments
  models/Comment.model.js
  public/css/styles.css
  public/js/commentReply.js
  routes/post.router.js
  views/partials/replyDialog.ejs
  views/postitems/post.ejs
Labels: GSSOC21, Level3, PR: reviewed-approved

#920 testimonial wall improved
  public/css/styles.css
  views/testimonials/testimonial-wall.ejs
Labels: GSSOC21, Level3, PR: reviewed-approved

#923 Updated banner in ReadMe file
  README.md
  assets/WordNook.png
  assets/Wordnook banner.png
Labels: PR: reviewed-approved

#922 fixed image not uploading on signup issue
  views/auth/signUp.ejs
Labels: PR: reviewed-approved

#933 fixed dashboard on mobile view #909
  public/css/styles.css
  views/useritems/dashboard.ejs
Labels: PR: reviewed-approved

#936 Update deploy
  README.md
  assets/WordNook.png
  assets/Wordnook banner.png
  models/Comment.model.js
  package-lock.json
  package.json
  public/css/styles.css
  public/images/wordnook logo.png
  public/js/commentReply.js
  routes/post.router.js
  views/auth/signUp.ejs
  views/partials/replyDialog.ejs
  views/postitems/post.ejs
  views/testimonials/testimonial-wall.ejs
  views/useritems/dashboard.ejs
Labels: PR: unreviewed

#945 Added feature to delete image from Blogpost issue#662
  routes/post.router.js
  views/postitems/post.ejs
Labels: GSSOC21, Level3, PR: reviewed-approved

#935 Update Technology Stack in Readme.md
  README.md
Labels: GSSOC21, Level2, PR: reviewed-approved

#930 Newsletter Feature
  .env.example
  app.js
  middlewares/newsletter.js
  models/User.model.js
  package-lock.json
  package.json
  routes/user.router.js
  views/newsletter.html
  views/useritems/dashboard.ejs
  views/useritems/newsletter.ejs
Labels: GSSOC21, Level3, PR: unreviewed

#953 Added separate router for newsletter
  app.js
  routes/newsletter.router.js
  routes/user.router.js
Labels: GSSOC21, Level3, PR: reviewed-approved

#951 Added a field in edit blog form to update image in the blog
  routes/post.router.js
  views/postitems/edit.ejs
Labels: GSSOC21, Level3, PR: reviewed-approved

#955 Deploy changes
  .all-contributorsrc
  .env.example
  README.md
  app.js
  middlewares/newsletter.js
  models/User.model.js
  package-lock.json
  package.json
  routes/newsletter.router.js
  routes/post.router.js
  views/newsletter.html
  views/postitems/edit.ejs
  views/postitems/post.ejs
  views/useritems/dashboard.ejs
  views/useritems/newsletter.ejs
Labels: PR: unreviewed

#960 Edit blog form
  public/css/styles.css
  views/postitems/edit.ejs
  views/useritems/read-profile.ejs
Labels: PR: reviewed-approved

#919 favicon updated #918 and Preloader is updated #835
  public/css/styles.css
  public/images/favicon.ico
  public/images/load.gif
Labels: GSSOC21, Level2, PR: reviewed-changes-requested

#962 fix: Handled footer in testinomials wall
  views/testimonials/testimonial-wall.ejs
Labels: GSSOC21, Level2, PR: reviewed-approved

#966 Husky feature
  .husky/.gitignore
  .husky/pre-commit
  package.json
  public/js/commentReply.js
Labels: GSSOC21, Level2, PR: reviewed-approved

#976 Added border and shadow to the post preview containers
  public/css/styles.css
Labels: GSSOC21, Level2, PR: reviewed-approved

#974 Login signup form
  views/auth/logIn.ejs
  views/auth/signUp.ejs
Labels: GSSOC21, Level2, PR: reviewed-approved

#972 prelaoder updated
  public/css/styles.css
  public/images/load.gif
  public/js/loader.js
  views/partials/header.ejs
Labels: GSSOC21, Level3, PR: reviewed-approved

#978 Added border to comments and replies
  public/css/styles.css
  views/postitems/post.ejs
Labels: GSSOC21, Level2, PR: reviewed-approved

#946 Solved issue with Box-Shadow in Nav-toggler
  public/css/styles.css
  views/partials/header.ejs
Labels: PR: reviewed-approved
