Repository ALPHAVIO/WordNook, pull requests merged in 2021-07, with the labels that each got.

#1037 Added missing "?"
  views/navitems/home.ejs
Labels: LGMSOC21, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, 🟪 Level0

#1048 Deploy dependency updates
  package-lock.json
  package.json
  views/navitems/home.ejs
Labels: PR: unreviewed

#1058 updatedReadme
  README.md
  assets/event4.png
  assets/event5.png
Labels: PR: reviewed-approved

#1059 Deploy Changes
  README.md
  assets/event4.png
  assets/event5.png
  package-lock.json
  package.json
Labels: PR: unreviewed

#1068 💄style: Improve Contact-Us form UI
  public/css/styles.css
  views/navitems/contact.ejs
Labels: LGMSOC21, PR: reviewed-approved, 🟧 Level3

#1073 Dockerized Wordnook
  .dockerignore
  .slugignore
  Dockerfile
  README.md
  docker-compose.yml
Labels: PR: unreviewed
