Repository ALPHAVIO/WordNook, pull requests merged in 2021-03, with the labels that each got.

#284 Add an additional note in issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: ready-to-merge, reviewed

#281 issue #280 resolved
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/assign.yaml
  .github/workflows/close-issue
  .github/workflows/close-pr.yml
  .github/workflows/gssoc.yml
  .github/workflows/level0.yml
  .github/workflows/level1.yml
  .github/workflows/level2.yml
  .github/workflows/level3.yml
  .github/workflows/merge.yml
  .github/workflows/review.yml
  README.md
  package-lock.json
  package.json
Labels: GSSOC21, Level1

#250 Documentation update
  README.md
Labels: GSSOC21, Level0, reviewed

#290 Add directories to store Models and Routes
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
  app.js
  models/Blog.model.js
  routes/index.router.js
  routes/post.router.js
  routes/user.router.js
Labels: GSSOC21, Level2, reviewed

#299 readmore bug fixed
  models/Blog.model.js
  routes/post.router.js
Labels: GSSOC21, Level2

#307 Changes in ISSUES Template and deleted automerge.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/automerge.yml
Labels: documentation

#302 Fixed margin under navbar
  package-lock.json
  public/css/styles.css
Labels: GSSOC21, Level2, reviewed

#247 Added workflow for GSSOC label
  .github/workflows/autoLabel.yaml
Labels: GSSOC21, Level2, reviewed

#322 Added tech stack logo
  README.md
Labels: GSSOC21, Level0

#287 Fixed comman url issue [issue #264]
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
  routes/post.router.js
  views/home.ejs
  views/post.ejs
Labels: GSSOC21, Level2, reviewed

#318 autoclose issue if corresponding PR gets merged
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/autoclose-issue.yml
  .github/workflows/automerge.yml
  .github/workflows/close-issue.yml
Labels: GSSOC21, Level2, reviewed

#312 Added like functionality
  app.js
  public/css/styles.css
  views/home.ejs
  views/post.ejs
Labels: GSSOC21, Level3, ready-to-merge, reviewed

#340 Added constraints for username & Password during signup
  routes/user.router.js
Labels: GSSOC21

#350 [UI] Update Login/Signup forms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/autoLabel.yaml
  README.md
  package-lock.json
  public/css/styles.css
  routes/user.router.js
  views/logIn.ejs
  views/signUp.ejs
Labels: GSSOC21, Level2

#356 file db.js is created inside config and promises is handled with mongoose
  app.js
  config/db.js
Labels: GSSOC21, Level2

#354 added contact form and route
  mail.js
  package-lock.json
  package.json
  routes/index.router.js
  views/contact.ejs
Labels: GSSOC21, Level3, reviewed

#379 Added update option on each post.
  package-lock.json
  package.json
  public/css/styles.css
  routes/post.router.js
  views/edit.ejs
  views/post.ejs
Labels: GSSOC21, Level2, reviewed

#383 Improve UI
  public/css/styles.css
  views/home.ejs
  views/partials/footer.ejs
  views/partials/header.ejs
Labels: reviewed

#392 Add confirm Password text box
  .github/PULL_REQUEST_TEMPLATE.md
  app.js
  models/User.model.js
  public/css/styles.css
  routes/user.router.js
  views/signUp.ejs
Labels: reviewed

#408 Optimization of sign-up code and style changes
  package-lock.json
  public/css/styles.css
  routes/user.router.js
  views/home.ejs
Labels: PR: unreviewed

#394 Improved UI
  views/contact.ejs
  views/home.ejs
  views/logIn.ejs
  views/partials/footer.ejs
  views/signUp.ejs
Labels: GSSOC21, Level2, reviewed

#395 login and signup button added
  public/css/styles.css
  views/partials/header.ejs
Labels: GSSOC21, Level2, PR: reviewed-approved, PR: unreviewed

#410 Positioning of social icons and button bug fixed
  public/css/styles.css
  views/partials/footer.ejs
Labels: GSSOC21, Level2, PR: reviewed-approved

#416 Feature date format
  app.js
  package-lock.json
  package.json
  public/css/styles.css
  views/home.ejs
  views/partials/footer.ejs
  views/post.ejs
Labels: GSSOC21, Level2, PR: reviewed-approved

#419 improved login and signup page
  views/logIn.ejs
  views/signUp.ejs
Labels: PR: unreviewed

#422 Create stale.yml
  .github/workflows/stale.yml
Labels: PR: unreviewed

#429 404 Page
  .github/workflows/stale.yml
  app.js
  package-lock.json
  package.json
  public/images/404.png
  views/404.ejs
  views/partials/header.ejs
Labels: PR: reviewed-approved

#431 Comments added on the right of 'Read More' button on home page for posts.
  views/home.ejs
Labels: GSSOC21, Level2, PR: reviewed-approved

#424 Added category field
  models/Blog.model.js
  routes/index.router.js
  routes/post.router.js
  views/category.ejs
  views/compose.ejs
  views/home.ejs
Labels: GSSOC21, Level3, PR: reviewed-approved

#426 password hashing is added as a middleware to the model
  models/User.model.js
  routes/user.router.js
Labels: GSSOC21, Level2, PR: reviewed-approved, slash-assigned

#430 Images Schema and routes created #315
  app.js
  models/Blog.model.js
  package-lock.json
  package.json
  routes/index.router.js
  uploads/2021-03-23T19-17-06.832Zmahadbt.jpg
  views/compose.ejs
Labels: GSSOC21, Level2, PR: reviewed-changes-requested, PR: unreviewed

#437 Reduce size of blog sneak-peek on home page
  views/home.ejs
Labels: PR: unreviewed

#443 Added /author/:id route
  assets/event3.png
  public/images/404.png
  public/images/bg2.jpg
  public/images/journalbg.jpg
  routes/index.router.js
  routes/post.router.js
  routes/user.router.js
  views/author.ejs
  views/category.ejs
  views/home.ejs
Labels: GSSOC21, Level2, PR: reviewed-approved, PR: unreviewed

#456 Switch username to email issue405
  package-lock.json
  package.json
  routes/user.router.js
  views/logIn.ejs
Labels: GSSOC21, PR: reviewed-approved

#448 removed close-issue.yml as it is not working
  .github/workflows/close-issue.yml
Labels: GSSOC21, PR: reviewed-approved

#454 issue #401 : added like button to the post page
  public/css/styles.css
  public/images/grey.png
  public/images/red.png
  views/home.ejs
  views/post.ejs
Labels: GSSOC21, Level2, PR: reviewed-approved

#444 Added /dashboard route
  routes/post.router.js
  routes/user.router.js
  views/dashboard.ejs
  views/logIn.ejs
  views/partials/header.ejs
  views/post.ejs
Labels: GSSOC21, Level3, PR: reviewed-approved, PR: unreviewed

#457 Update master
  .github/workflows/close-issue.yml
  app.js
  models/Blog.model.js
  package-lock.json
  package.json
  routes/index.router.js
  routes/post.router.js
  routes/user.router.js
  uploads/2021-03-23T19-17-06.832Zmahadbt.jpg
  views/author.ejs
  views/category.ejs
  views/compose.ejs
  views/dashboard.ejs
  views/home.ejs
  views/logIn.ejs
  views/partials/header.ejs
  views/post.ejs
Labels: PR: unreviewed

#461 Update develop
  public/images/grey.png
  public/images/red.png
  uploads/2021-03-23T19-17-06.832Zmahadbt.jpg
Labels: PR: unreviewed

#469 ContactUS Formatting
  public/css/styles.css
  views/contact.ejs
Labels: PR: reviewed-approved

#479 Update README.md
  README.md
Labels: GSSOC21, Level1, PR: unreviewed

#467 Removed short content from blog cards
  views/author.ejs
  views/category.ejs
  views/dashboard.ejs
  views/home.ejs
  views/partials/posts.ejs
Labels: PR: reviewed-approved

#477 Alignment of buttons
  public/css/styles.css
  views/home.ejs
Labels: GSSOC21, Level2, PR: reviewed-approved

#490 Update deploy branch
  README.md
  public/css/styles.css
  views/author.ejs
  views/category.ejs
  views/contact.ejs
  views/dashboard.ejs
  views/home.ejs
  views/partials/posts.ejs
Labels: PR: unreviewed

#496 fix(post) : Fixed edit post bug
  routes/post.router.js
Labels: GSSOC21, PR: reviewed-approved

#493 Added sneak peek
  views/partials/posts.ejs
Labels: GSSOC21, Level2, PR: reviewed-approved, PR: unreviewed

#494 fix(blog-post): fixed the system for adding images to blogpost
  routes/index.router.js
  routes/post.router.js
  views/post.ejs
Labels: PR: reviewed-approved

#484 user edit page is added
  package-lock.json
  package.json
  routes/index.router.js
  routes/user.router.js
  views/partials/header.ejs
  views/read-profile.ejs
Labels: PR: reviewed-changes-requested

#498 Update deploy branch
  package.json
  routes/index.router.js
  routes/post.router.js
  routes/user.router.js
  views/partials/header.ejs
  views/partials/posts.ejs
  views/post.ejs
  views/read-profile.ejs
Labels: PR: unreviewed

#499 center align compose button for mobile and tablet view issue #491
  views/home.ejs
Labels: PR: reviewed-approved

#501 Added status field
  app.js
  models/Blog.model.js
  routes/index.router.js
  routes/post.router.js
  routes/user.router.js
  views/author.ejs
  views/compose.ejs
  views/home.ejs
Labels: GSSOC21, Level3, PR: reviewed-approved

#507 Update deploy branch
  app.js
  models/Blog.model.js
  routes/index.router.js
  routes/post.router.js
  routes/user.router.js
  views/author.ejs
  views/compose.ejs
  views/home.ejs
Labels: PR: unreviewed

#510 Fix prod bug
  .prettierrc.json
  package-lock.json
  package.json
  routes/index.router.js
Labels: PR: unreviewed

#511 chore: update deploy branch
  .prettierrc.json
  package-lock.json
  package.json
  routes/index.router.js
Labels: PR: unreviewed

#505 fixed mobile-nav
  views/partials/header.ejs
Labels: PR: unreviewed

#516 Improved the position of hamburger icon
  views/partials/header.ejs
Labels: GSSOC21, PR: reviewed-approved

#523 Weekly Digest
  .github/workflows/weekly-digest.yml
Labels: PR: unreviewed

#525 Update README.md
  README.md
Labels: PR: unreviewed

#508 Updated /posts/:id/edit route
  routes/post.router.js
  views/dashboard.ejs
  views/edit.ejs
Labels: PR: reviewed-changes-requested

#531 Updated readme.md
  README.md
Labels: PR: unreviewed

#530 moved mail.js to middlewares
  middlewares/mail.js
  routes/index.router.js
Labels: PR: unreviewed

#536 Updated /dashboard UI
  routes/index.router.js
  routes/post.router.js
  views/dashboard.ejs
  views/partials/footer.ejs
  views/partials/header.ejs
  views/partials/posts.ejs
Labels: PR: reviewed-approved

#535 refactor(routes): refactor routes
  routes/index.router.js
  routes/post.router.js
  routes/user.router.js
Labels: GSSOC21, Level2, PR: reviewed-approved

#540 chore: update deploy
  .all-contributorsrc
  .github/workflows/weekly-digest.yml
  .prettierrc.json
  README.md
  middlewares/mail.js
  routes/index.router.js
  routes/post.router.js
  routes/user.router.js
  views/dashboard.ejs
  views/edit.ejs
  views/partials/footer.ejs
  views/partials/header.ejs
  views/partials/posts.ejs
Labels: PR: unreviewed
