Repository ALPHAVIO/WordNook, pull requests merged in 2021-06, with the labels that each got.

#947 Added captcha in singUp form
  package-lock.json
  package.json
  routes/user.router.js
  views/auth/signUp.ejs
  views/partials/header.ejs
Labels: GSSOC21, Level3, PR: reviewed-approved, PR: unreviewed

#994 Make recaptcha only for production
  .eslintrc.json
  README.md
  routes/user.router.js
Labels: PR: unreviewed

#1004 Added transition on testimonial cards.
  public/css/styles.css
Labels: LGMSOC21, Level2, PR: reviewed-changes-requested

#1007 added LGM-SOC to README
  README.md
  assets/event4.png
Labels: LGMSOC21, PR: reviewed-approved, 🟩 Level1

#1009 Maintainers card added
  README.md
Labels: PR: unreviewed

#1011 Add maintainer card
  README.md
Labels: PR: unreviewed

#1013 Removed text shadow in footer.
  public/css/styles.css
  views/partials/footer.ejs
Labels: LGMSOC21, PR: reviewed-approved, 🟩 Level1

#1020 Update Overlapping buttons in carousel
  public/css/styles.css
Labels: PR: reviewed-approved

#1024 FIx Size of delete button in Firefox
  public/css/styles.css
Labels: LGMSOC21, Level1, PR: reviewed-approved

#1021 Bug in profile image sizing
  public/css/styles.css
Labels: PR: reviewed-changes-requested

#1029 Testimonial made Persistant
  models/Testimonial.model.js
  routes/testimonial.router.js
  views/testimonials/testimonial-wall.ejs
Labels: LGMSOC21, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed, 🟧 Level3

#1031 Deploy changes
  .eslintrc.json
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/labels.json
  .github/workflows/autoLabel.yaml
  .github/workflows/issue-label.yml
  .github/workflows/level4.yml
  README.md
  assets/event4.png
  models/Testimonial.model.js
  package-lock.json
  package.json
  public/css/styles.css
  routes/testimonial.router.js
  routes/user.router.js
  views/partials/footer.ejs
  views/testimonials/testimonial-wall.ejs
Labels: PR: unreviewed
